### ISSUE TITLE
Evaluate core XDR change impact for removing ContractCostType::ComputeEcdsaSecp256k1Key

### ISSUE THREAD

**Issue by anupsdf** [stellar/soroban-tools#1001]
### What?
Evaluate core XDR change impact for removing ContractCostType::ComputeEcdsaSecp256k1Key in upcoming issue https://github.com/stellar/rs-soroban-env/issues/1087

**Comment by mollykarcher** [comment]
Closing in favor of https://github.com/stellar/go/issues/5075
