### ISSUE TITLE
Evaluate core soroban-env-host error handling changes 

### ISSUE THREAD

**Issue by anupsdf** [stellar/soroban-tools#1002]
### What version are you using?
Evaluate the impact of core soroban-env-host error handling changes in
https://github.com/stellar/rs-soroban-env/commit/44cba6a72cd2cca9594de492298eea1a7ed0e031
https://github.com/stellar/rs-soroban-env/commit/1c3f7aef810c2692ee0c9ef2bfc690d9cbb8d647
https://github.com/stellar/rs-soroban-env/commit/94bc87a42d5ced70905f2c09f6ae69fa000954ba

**Comment by 2opremio** [comment]
@anupsdf without a summary of what changed, it's more productive to simply try the new version `rs-soroban-env` and see the impact. Can you give me the env and SDK commits so that I try it out?

**Comment by mollykarcher** [comment]
Closing in favor of https://github.com/stellar/go/issues/5075
