### ISSUE TITLE
Evaluate core PRNG calibration change impact

### ISSUE THREAD

**Issue by anupsdf** [stellar/soroban-tools#1003]
### What?
Evaluate core PRNG calibration change impact in https://github.com/stellar/rs-soroban-env/commit/f5938009b3828359f403e6c78c544d94b626fe9e

**Comment by tamirms** [comment]
we might want to add an integration test that invokes preflight on a smart contract that uses prng so we can confirm that the fees are calculated correctly by preflight.

**Comment by 2opremio** [comment]
Created https://github.com/stellar/soroban-tools/issues/1005

**Comment by mollykarcher** [comment]
Closing in favor of #1005
