### ISSUE TITLE
The contract ID returned by `getEvents` should be a strkey

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-tools#1007]
The hex-encoded form has been considered deprecated for a long time, and it's actually not even supported in some SDKs anymore to encourage the use of the strkey version (`C...` form). 

Note that this would be a breaking change.

**Comment by sydneynotthecity** [comment]
should be worked in tandem with #998

**Comment by Shaptic** [comment]
According to the codebase (here: [`methods/get_events.go`](https://github.com/stellar/soroban-tools/blob/main/cmd/soroban-rpc/internal/methods/get_events.go#L419-L421)), this is already being done! 

That means the documentation just needs to be updated.

I've adjusted this to 1 point to scope that work.

**Comment by Shaptic** [comment]
Completed by https://github.com/stellar/soroban-docs/pull/605.
