### ISSUE TITLE
Update the Protocol 20 community SDK issues with new XDR/API changes

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-tools#1009]
Once the XDR and API are stabilized, we will need to inform the community SDK maintainers about the changes.

The CLI script can add comments rather than open new issues, but a new issue is better given that many SDK repos have already closed the Protocol 20 issues (e.g. https://github.com/Soneso/stellar_flutter_sdk/issues/73).

### XDR
The XDR needs to be updated to https://github.com/stellar/stellar-xdr/commit/6a620d160aab22609c982d54578ff6a63bfcdc01. This includes a non-trivial list of breaking changes (mostly renames):
  - The `BumpFootprintExpirationOp` is now `ExtendFootprintTTLOp` and its `ledgersToExpire` field is now named `extendTo`, but it serves the same purpose.
  - `ContractExecutable.contractExecutableToken` is now `contractExecutableStellarAsset`
  - `SorobanTransactionData.refundableFee` is now `resourceFee`
  - This new fee encompasses the entirety of the Soroban-related resource fees. Note that this is distinct from the "network-inclusion" fee that you would set on your transaction
  - see https://github.com/stellar/js-stellar-base/pull/704 for an example migration

### RPC
 - The `getEvents` RPC endpoint structure has changed:
   * `value: { xdr: string }` is now just `value: string` (https://github.com/stellar/soroban-tools/pull/1015)
   * `contractId` will always be a contract strkey (`C...` format) if present (https://github.com/stellar/soroban-tools/issues/1007)
 - The `getLedgerEntries` RPC endpoint now includes expiration info (https://github.com/stellar/soroban-tools/pull/1010):
   * `expirationLedgerSeq` is a string-ified `uint32` present if the requested entries have expiration

**Comment by 2opremio** [comment]
I would explicitly mention the XDR symbol renames, and the operation BumpFootprintExpiration->ExtendFootpintTTL rename in particular
