### ISSUE TITLE
soroban-rpc: Better state expiration support for `getLedgerEntry`

### ISSUE THREAD

**Issue by dmkozh** [stellar/soroban-tools#1010]
Currently `getLedgerEntry` endpoint just returns the LE XDR, which now doesn't have the expiration-related info.

Instead it probably should:
- Return the entry expiration ledger (fetched from the respective `EXPIRATION` entry), when applicable
- Return a flag denoting whether entry has expired, when applicable

This would make the behavior consistent with simulation, where we already do fetch and mark the restored entries (when available).

**Comment by Shaptic** [comment]
Related, as a more-immediate workaround: https://github.com/stellar/js-soroban-client/issues/153

**Comment by sreuland** [comment]
> I don't believe that `Return a flag denoting whether entry has expired, when applicable` is really needed

sounds good, so, the net change would reduce to just new `LedgerEntryResult.ExpirationLedger`, with additional behavior of:

1. it's optional, will be absent if not applicable for LE?
2. if present it could be 0 meaning the LE has no expiration, or non-zero indicates a real ledger number that LE will expire upon.

**Comment by tsachiherman** [comment]
If it returns, the LE definitely has an expiration. The only question is whether a value of 0 is the right way to say "I don't know which ledger sequence it was expired upon" or whether we should find another way to achieve that.
I think that it's not a decision we have to make right now.

**Comment by sreuland** [comment]
> If it returns, the LE definitely has an expiration. The only question is whether a value of 0 is the right way to say "I don't know which ledger sequence it was expired upon" or whether we should find another way to achieve that. I think that it's not a decision we have to make right now.

ok, is there a provision in spec for any type of LE's to not expire, and therefore have no expiration ledger, where `0` could denote that?

**Comment by tsachiherman** [comment]
of course. only contract_data and contract_code would expire.. all the rest of the entries have no expiration associated with them ( at least for now ).
