### ISSUE TITLE
soroban-cli: rename `config identity` to `config key`

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#1053]
I think we should consider renaming `config identity` to `config key`.

Keys are buried in the soroban-cli under the `config identity` command. It's easy to miss it and think the soroban command doesn't do key generation or key management.

While identity is a nice name for a number of reasons of why we picked it, it reduces the discoverability.

**Comment by willemneal** [comment]
We could also do top level
- `keys`
- `id`

This would let you have named public addresses including contracts.

**Comment by leighmcculloch** [comment]
I think there's value in keeping a local address book separate to keys. To make it really clear what are keys a user owns vs other addresses. 

i.e.:
- `soroban key`
- `soroban addressbook`

**Comment by willemneal** [comment]
What is confusing though is a key also has an address. So anywhere we use an `Address` in the CLI should use either when converting the alias to address. So we prioritize one namespace over the other? Or ensure that aliases are unique across them.

Alternatively we could also have prefixes on the addresses. E.g.`C:` `G:`, and `S:`?

**Comment by leighmcculloch** [comment]
Could you share some examples of what you mean?

**Comment by willemneal** [comment]
For starters, if you have `foo` as both a key and in the address book then when using the alias which would be picked.

`K:foo` would refer to the address of the secret key foo, while `A:foo` would be the address book. Or we could avoid that all together and say they both share the same namespace.

**Comment by leighmcculloch** [comment]
Rather than prefixes I'd make it a unified space where the addressbook is a superset of the keys, and registering an address in the addressbook under a name that has a key or vice versa would be an error.
