### ISSUE TITLE
soroban-cli: move `config *` commands to top level

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#1054]
I think we should consider moving the commands that live under `soroban config` to the top level.

i.e.:

`config identity` => `key` (assuming #1053)
`config network` => `network`

The `network` and `identity` commands are buried under config which makes them hard to find. They're important concepts that devs need to access regularly.

We should bury things under config if they're a set once and forget type of thing.

In reality devs need to interact with keys frequently. And likely need to switch and use multiple networks frequently too.

**Comment by willemneal** [comment]
True, the subcommand doesn't add much value, and soon we'll need a `network start` which definitely should be at the top level.
