### ISSUE TITLE
soroban-cli: uses the same identity/account/key for everybody by default

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#1079]
### What version are you using?

```console
$ soroban version
soroban 20.0.0-rc.4.2 (v20.0.0-rc.4.1-4-g4e9a48756b96e4e1a070105bad202f39901139ad-dirty)
soroban-env 20.0.0-rc2 (8c63bff68a15d79aca3a705ee6916a68db57b7e6)
soroban-env interface version 85899345977
stellar-xdr 20.0.0-rc1 (d5ce0c9e7aa83461773a6e81662067f35d39e4c1)
xdr curr (9ac02641139e6717924fdad716f6e958d0168491)
```

### What did you do?

Used the default identity:

```console
$ soroban config identity address
```

### What did you expect to see?

A non-shared address. Maybe randomly generated on first use.

### What did you see instead?

An address and key that everybody who is using the soroban-cli will use by default.

```
GDIY6AQQ75WMD4W46EYB7O6UYMHOCGQHLAQGQTKHDX4J2DYQCHVCR4W4
```

### Why is this a security bug?

It's surprising that any key is shared.

Tooling that provides any shared key runs the risk of causing someone to think they have a unique key when they don't. Somebody may use the key on mainnet thinking it is a key unique to themselves.

### Why is this a general bug?

Developers who use the default identity will be contending for access to the network. The network will only allow one tx per account in each ledger.

**Comment by willemneal** [comment]
True, my thought was that it was useful for generating the same transactions for testing across CI and teams. But it's not that hard to generate a test account with the default seed. This was also when we thought people would use the sandbox.

I vote the first option. Better to be explicit.

**Comment by leighmcculloch** [comment]
For CI testing predictability is still helpful so I think we'd still want to use some common key in CI.

**Comment by willemneal** [comment]
Yeah that was what I was saying.
```
soroban config identity generate --default-seed
```
Is equivalent to
```
soroban config identity generate --seed 0000000000000000
```

Then you can use `--hd-path` for generating multiple accounts.

**Comment by leighmcculloch** [comment]
I don't think we've explicitly said here, but I believe we have agreed to remove the default identity.

cc @mollykarcher if you remember otherwise.

**Comment by mollykarcher** [comment]
Yes, that's my understanding as well
