### ISSUE TITLE
Fix check-dependencies script

### ISSUE THREAD

**Issue by tamirms** [stellar/soroban-tools#1110]
There is a bug in the check dependencies [script](https://github.com/stellar/soroban-tools/blob/main/scripts/check-dependencies.bash#L35) which is causing the "Dependency sanity checker" CI failure. The script relies on the fact that the git and rev properties would be supplied for the stellar-xdr dependency. However, those properties were commented out of the stellar-xdr dependency in the rs-soroban-env repo https://github.com/stellar/rs-soroban-env/blob/main/Cargo.toml#L31-L32 .

**Comment by mollykarcher** [comment]
Link to [slack discussion](https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1701793185697229)

We should likely be able to scrap the script (or at least part of it) in favor of cargo-deny, which other rust repos currently use. However, that script is also checking go dependencies (not just rust) to make sure xdr versions match up, so we may need some hybrid or an alternative if that's still needed.
