### ISSUE TITLE
enable independent releases of soroban-rpc and soroban-cli

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-tools#1115]
### What problem does your feature solve?

Currently, RPC and CLI are always versioned together when released. These are different products with different release lifecycles. It's likely that CLI will have a tendency to iterate faster than RPC as soroban matures. However, if CLI-only changes are made, RPC still gets version bumped. This means that semantic versioning can't be properly followed for both of these tools.

### What would you like to see?

A release process / CD pipeline that allows us to independently version and release soroban-rpc and soroban-cli. 

### What alternatives are there?

- Move them into separate repos entirely
- Keep versioning them together. It's not clear to me what benefit this provides, but all ears if someone has more context

**Comment by leighmcculloch** [comment]
All of the Rust repos in the @stellar org share the same release process. Rather than introduce a new release process for the CLI to support releasing the CLI + RPC independently from within the same repo, I'd like to see it maintain the same release process that the Rust repos use. Rust projects are not trivial to release, and over time having a single release process for all our Rust projects will help us maintain a consistent and secure release process for these projects.

**Comment by janewang** [comment]
Agreed, I believe the plan is to restructure this repo. CLI will live in its own repo, be renamed from Soroban CLI to Stellar CLI, has a README available at the top level, and has its own release cadence.

**Comment by willemneal** [comment]
I split the RPC into its own crate in this PR https://github.com/stellar/soroban-tools/pull/1065. Which is the first step toward your last point.

**Comment by leighmcculloch** [comment]
> Agreed, I believe the plan is to restructure this repo. CLI will live in its own repo, be renamed from Soroban CLI to Stellar CLI, has a README available at the top level, and has its own release cadence.

+1. For the sake of preserving the most git history and git sha's possible, I suggest we keep this repo as the soroban-cli, because this repo started out as the soroban-cli repo. Later on soroban-rpc was moved into this repo.

**Comment by stellarsaur** [comment]
As of now, we're able to release [Soroban RPC separately from CLI](https://github.com/stellar/soroban-rpc/blob/main/RELEASING.md).

Please refer to [this tracking issue](https://github.com/stellar/soroban-tools/issues/1171) for what's left in terms of clean up
