### ISSUE TITLE
CLI: Add logging output to serve subcommand

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#135]
### What problem does your feature solve?

`soroban-cli serve` would be slightly nicer to use if you could tell what is going on. It would help debug clients, as you could tell if they actually made the request you expected.

### What would you like to see?

Some sort of logging output when `serve` handles a request.

**Comment by leighmcculloch** [comment]
+1 It could also log debug events which are contract logs.

**Comment by leighmcculloch** [comment]
Serve command is no more, so I think this can be closed.
