### ISSUE TITLE
CLI: Add identity / profile concept

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#173]
@paulbellamy just shared this idea with me, and I think it would go a long way to improving the experience of using the cli.

Developers using the soroban-cli need to manage several things together:
- Keys for real world deployment
- Network configuration for whether they are using sandbox, futurenet, testnet, pubnet, etc.
- Possibly other things in the future such as a salt counter

Today they must manage those things themselves and pass them into the correct via arguments. It's important that these things are always available as arguments for things like scripting, but for a developer sitting at a command line having to repeatedly enter these values is annoying and error prone.

The fact it is annoying to enter all these details has led us to design some commands for sandbox in ways that diverge from the real world command they mimic. For example, deploying to sandbox takes a contract ID, where as deploying to real world takes a signing key and salt that is used to produce the ID.

If using the real world command line options were simpler, by having them all be default values from a configured identity / profile, using a real world set of options for sandbox would be much more achievable.

The idea is to have a command such as `identity` that manages multiple identities that contains all these configurations. The developer would then choose which identity they were using when running commands.

Here are some example flows:

Create a new identity that would generate a new key, and configure for the network:
```
soroban identity new --name ABC --network pubnet
```

Create a new identity with custom config:
```
soroban identity new --name ABC --rpc-url ... --network-passphrase ...
```

List available identities:
```
soroban identity ls
```

Select the identity for use and use it for deploys and reads:
```
soroban identity use ABC
soroban deploy --wasm myfile.wasm
```

Select an identity for a specific command
```
soroban --identity ABC deploy --wasm myfile.wasm
```

The default identity could be an identity called `sandbox` which generates a key on first use automatically and configures for local use.

The developer may forget that they have a pubnet identity in use and run a command not intended for pubnet, so it would probably be pertinent to add in a confirmation whenever a command is in use with pubnet.

**Comment by tomerweller** [comment]
Awesome idea. 

I prefer the term "Profile" over "Identity" so that we don't limit ourselves to identity related configuration. Furthermore, I would consider using these profiles as a generic way to provide default values for any argument, not just pre-determined ones, so that this feature is forward compatible with new configuration that we add in the future.

**Comment by paulbellamy** [comment]
As @leighmcculloch and I discussed, aws-cli calls this a "Context", but that feels too generic. I've come around to "Profile", as a good term for this thing. It's somewhat key-centric (like "Identity", or "Account"), but gives space for more general config (network + etc).

**Comment by sreuland** [comment]
sounds good, wanted to mention [kubectl config](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) for reference also with a range of users being familiar with it, has similar 'profile' patterns with a cli, like the ability to specify the config file to load profiles from, assuming this has to write these settings somewhere on disk. it uses 'Context' terminology also.

**Comment by leighmcculloch** [comment]
👏🏻 I think this has been delivered upon with the config impl. Please reopen if I'm wrong about that.
