### ISSUE TITLE
CLI: Redesign

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#197]
There's a few issues with the CLI's top-level surface area and how the commands are organized. We have got issues open for those specific things (#165 #173), but I think we need to take a step back and rethink the design of the CLI.

This is a tracking issue, for tracking the problem and coordinating, but the design itself is in the below Google Document. The document is publicly accessible and can be commented on by anyone.

https://docs.google.com/document/d/1zV_F3WMPbxOuXxAknGFocXLOB5X_LcHBF4LG-AF8BUo

**Comment by willemneal** [comment]
Newest proposal is here: https://docs.google.com/document/d/16lJhyMU6cqRzNtMclr9yXd978MJgbZ0El9UhxbTz_Ts/edit?usp=sharing

**Comment by leighmcculloch** [comment]
Closing this issue as we're moving ahead with the proposal, and issues can be opened for specific areas for implementation.
