### ISSUE TITLE
soroban tooling: refactor, compile time reference to cli as dependency, spike

### ISSUE THREAD

**Issue by sreuland** [stellar/soroban-tools#240]
epic - https://github.com/stellar/go/issues/4672

depends on https://github.com/stellar/go/issues/4679

### What problem does your feature solve?
other modules to have compile time dependency on cli(tooling)

### What would you like to see?
A spike that determines how other modules can compile with a dependency to cli(tooling) - instead of importing crates, use gitmodule to compile against explicit source code.

**Comment by paulbellamy** [comment]
> other modules to have compile time dependency on cli(tooling)
Is there an example that would make it more clear what you're talking about?

**Comment by tsachiherman** [comment]
I think we can close this one, right ?

**Comment by sreuland** [comment]
yes, tools refactor has been integrated into repos for a while, this looks like it was tracking a sub-task of that.
