### ISSUE TITLE
Remove circular dependency on quickstart repo

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#287]
To run the `Rust -> e2e tests` github action (required for merging PRs), this repo uses the [quickstart docker image](https://github.com/stellar/quickstart/), which includes soroban-rpc (from this repo).

The result is that if you make a breaking change to soroban-rpc, the e2e tests will block you from merging it.
[Example](https://github.com/stellar/soroban-tools/pull/270)

We should resolve that circular dependency. Some options:
- stop using quickstart image in e2e tests. Maybe simpler, but makes them less realistic.
- make the e2e step rebuild quickstart with local changes
- something else?

**Comment by jcx120** [comment]
Only affects testing (not compilation), dependency should be fixed. Refactor integration tests. Mostly for CLI tests. get feedback on PR (via system tests).
