### ISSUE TITLE
soroban-cli: Improve cli arg parsing

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#332]
### What problem does your feature solve?

How to encode and pass args to `soroban invoke ... --arg ??` is a continual stumbling point for new users.

### What would you like to see?

We should do a 2-day spike to write a few proposals with ways we could improve this. See how other ecosystems and analogies do it. Check the discord for the issues or talk to @tyvdh people are finding. @willemneal , and AhaLabs folks may have thoughts on this.

### Related
https://github.com/stellar/soroban-tools/issues/330
https://github.com/stellar/soroban-tools/issues/285
https://github.com/stellar/soroban-tools/issues/126
https://github.com/stellar/soroban-tools/issues/44

**Comment by paulbellamy** [comment]
cc @willemneal & @chadoh , I believe you guys are working/worked on this, yeah?

**Comment by willemneal** [comment]
Yep #307 added the ability to pass in args as cli arguments after `--` And provides a nice help doc with `-- --help`

**Comment by paulbellamy** [comment]
Right. Seems like this is done then! Thanks!

**Comment by oggy107** [comment]
> Yep #307 added the ability to pass in args as cli arguments after `--` And provides a nice help doc with `-- --help`

Thanks alot `-- --help` saved my life :>
