### ISSUE TITLE
xdr: update go monorepo XDR

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#347]
### What ? 

We need to update the go monorepo XDR to the latest XDR that supports AuthNext.
That would allow the dependent soroban-rpc to take advantage of it.

PR in go monorepo : https://github.com/stellar/go/pull/4756

this issue is part of the authNext efforts, which are covered in https://github.com/stellar/soroban-tools/issues/346

**Comment by paulbellamy** [comment]
XDR to update is in this PR https://github.com/stellar/stellar-xdr/pull/65
