### ISSUE TITLE
soroban-rpc: Update SimulateTransaction code to support authNext

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#348]
### What

Update SimulateTransaction code to support authNext

**Comment by paulbellamy** [comment]
- Update the rust dependency on rs-soroban-env
- Return the new authorizations result from simulate_transaction back to the client.

**Comment by paulbellamy** [comment]
Doc updates for this are in https://github.com/stellar/soroban-docs/pull/291

**Comment by paulbellamy** [comment]
https://github.com/stellar/rs-soroban-env/pull/645/ is in review now, so we could use that git revision to start work before it is merged.
