### ISSUE TITLE
dapp example: update to support AuthNext

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#351]
### What ?

update to support AuthNext

**Comment by jcx120** [comment]
Contract updates, replace invoker
Assumption: no freighter changes

**Comment by paulbellamy** [comment]
Waiting for https://github.com/esteblock/soroban-react/pull/21, then https://github.com/stellar/quickstart/pull/424, and finally https://github.com/stellar/soroban-example-dapp/pull/87
