### ISSUE TITLE
soroban-cli: config subcommand usability improvements

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#400]
I'd suggest we should:
- Throw a more informative error if we are trying to use a network with no identity configured. Currently it just says something like, "failed to parse secret key".
- Add a pair of `soroban config identity|network default` commands to show/set the default for each. Currently you can only set them as default when creating the network or identity.
- Actually handle the `--default` flags to do something. Currently afaict it does nothing.

**Comment by willemneal** [comment]
Incoming PR for the 1.

As for the second two, I meant to remove the `--default` all together.  We initially had the default commands, but came to realize that 1) it might be a foot gun for users.  That is using the identity unintentionally. 2)  We currently either pass the network arguments or `--network` as the mechanism that determines whether we use the network.

One thought is that you can name the networks and the identity default.

```bash
soroban contract invoke --id aa --network default --identity default ...
```

Wdyt?

**Comment by paulbellamy** [comment]
Thinking about this more. What if we kept the `default` behaviour, and added a warning when (pseudocode):
```ts
  (identity == default || network == default) &&
  (!txn.footprint.readWrite.isEmpty() || !txn.auth.requiredSignatures.isEmpty())
```
Then when you try to:
```bash
$ soroban contract invoke --id token --fn burn -- --amount 5 # or some other destructive txn
Sending transaction with:
  Identity: default
  Network: default
  Contract ID: CA3D5KRYM6CB7OWQ6TWYRR3Z4T7GNZLKERYNZGGA5SOAOPIFY6YQGAXE
  Method: burn
  Arguments: 5
  
Do you want to send this transaction? [y/N]
```
And added an `soroban contract invoke -y` (or `-f`?) arg for scripts to explicitly disable the prompt.

(Or we could always prompt if identity or network are missing, not based on the txn. That might make it more predictable.)

**Comment by paulbellamy** [comment]
And one other idea, actually. Maybe w should support `echo "MY_SECRET" | soroban config identity add foo --secrey-key -` so that scripts can create keys...
