### ISSUE TITLE
soroban-cli: Add `config identity address ...` subcommand

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#405]
### What problem does your feature solve?

Right now, the identity file stores the secret key. But it would be nice to be able to retrieve the address of an identity as well. Sometimes you want to pass that as an arg, or use it in scripts.

### What would you like to see?

Add a command like:
```
$ soroban config identity address paul
GDT2NORMZF6S2T4PT4OBJJ43OPD3GPRNTJG3WVVFB356TUHWZQMU6C3U
```

**Comment by Shaptic** [comment]
Closing because this appears addressed in v0.6.0. I see it:

```
$ soroban config identity address george                                                                                                                                        2 ↵
GAHNQN336E3FS32P2C4RSHDRVML65ECJPLHQ6O5VYND6XVUHADI3ULAJ
```

but reopen if not.
