### ISSUE TITLE
soroban-rpc: deploy public instance on futurenet

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-tools#418]
### What problem does your feature solve?

We'd like to facilitate more engagement/usage of RPC in the ecosystem prior to launching on testnet. We eventually plan to host a public instance on testnet as well, but not pubnet.

### What would you like to see?

A deployed public instance of soroban-rpc on futurenet on stellar domain,`rpc-futurenet.stellar.org`. Deployment should be integrated into the soroban release process so that it receives updates appropriately.

Initial deployment to use k8s and the quickstart soroban-dev image for soroban rpc, and ingress route for dns.

This initial deployment will later be refactored to use new rpc service deployment image from #382 and updated helm chart to use/config that image.

### What alternatives are there?
- #382 as a pre-requisite/blocker
- quickstart in its current form (potentially faster/easier, but to be followed up prior to testnet release by #382)

**Comment by Shaptic** [comment]
> We eventually plan to host a public instance on testnet as well, but not pubnet.

Are we sure this is a good precedent to set? I'd rather see deployments be as simple and streamlined as possible.

**Comment by jcx120** [comment]
Ops ticket for reference: 
https://github.com/stellar/ops/issues/2165

**Comment by sreuland** [comment]
k8s manifest for the deployment is up for review. 

https://github.com/stellar/soroban-tools/pull/470

coordinating with ops for next steps on [stellar/ops#2165 discussion](https://github.com/stellar/ops/issues/2165#issuecomment-1454220635)

**Comment by sreuland** [comment]
the manfiests for prd deployment up for review - https://github.com/stellar/kube/pull/1337

**Comment by leighmcculloch** [comment]
@sreuland @tomerweller Do we need [stellar-futurenet.4d63.com/](https://stellar-futurenet.4d63.com/) anymore?

**Comment by tomerweller** [comment]
no. we have rpc-futurenet.stellar.org

**Comment by willemneal** [comment]
@tomerweller Should we add this to CLI? Have a special `futurenet` network so you can do `--network futurenet` or `SOROBAN_NETWORK=futurenet` without having to manually add it?

**Comment by tomerweller** [comment]
@willemneal yes I like that idea!
