### ISSUE TITLE
soroban-cli: Can't use an `--identity` when deploying a contract.

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-tools#425]
### What version are you using?
0.6.0

```
$ soroban version                                                                                                                                                             130 ↵
soroban 0.6.0 (7421c1383beae274d41e503fa44e248b1dbe9b05)
soroban-env 0.0.14 (d06aaddca61f011cc64ec098b464233423197c3a)
soroban-env interface version 29
stellar-xdr 0.0.14 (55f47d302a3bbcd34cf32bfcd28abccfaeffc5e0)
xdr next (df18148747e807618acf4639db41c4fd6f0be9fc)
```

### What did you do?
Tried deploying a contract using an identity:

```bash
soroban config identity generate george
soroban contract deploy \                                                                                                                                                   130 ↵
    --wasm [...] \
    --identity george \
    --rpc-url http://localhost:8000/soroban/rpc \
    --network-passphrase 'Standalone Network ; February 2017'
```

### What did you expect to see?
A deployed contract hash.

### What did you see instead?
An error about `--secret-key` being required:

```
error: The following required arguments were not provided:
    --secret-key <SECRET_KEY>
```

I believe this is because the `--rpc-url` parameter marks the `--secret-key` parameter as required, while it should in fact allow **either** the secret key or the `--identity` parameter:

https://github.com/stellar/soroban-tools/blob/55487b2f8f0432bd3c2c2848f52e91772f02c94d/cmd/soroban-cli/src/config/network/mod.rs#L48-L58

**Comment by willemneal** [comment]
@Shaptic Until #426 is merged, this should work currently if you add the network to the config and then use `--network`.

**Comment by Shaptic** [comment]
Thanks for the quick PR! I did discover that as a workaround :)
