### ISSUE TITLE
soroban-rpc: production improvements

### ISSUE THREAD

**Issue by 2opremio** [stellar/soroban-tools#435]
We should:

1. Add timeouts where needed (e.g. when accessing other services, when filling the DB)
2. Analyze where things can fail and add retries were needed (e.g. when accessing the History archive service)
    For instance, at startup, wait for the first checkpoint if need be (otherwise soroban-rpc fails right away)
4. Go over the TODOs/FIXMEs

**Comment by tsachiherman** [comment]
merged into https://github.com/stellar/soroban-tools/issues/483
