### ISSUE TITLE
Update Example DApp for RPC: GetEvents

### ISSUE THREAD

**Issue by jcx120** [stellar/soroban-tools#458]
[Epic](https://github.com/stellar/soroban-tools/issues/457)

depends on [js-client-sdk update](https://github.com/stellar/js-soroban-client/issues/2) 

Update the Fundraising example DApp to provide working demo of getEvent(ContractID) in action:

- [ ] Provide fixture to generate multi-player events (ie for new contributions to funding Account)
- [ ] Asynchronously update DApp to update total fundraising amount (and list of donors)
- [ ] Update individual account balances
- [ ] Testing:
   - Wire in soroban on react (community lib) for testing

**Comment by sreuland** [comment]
@paulbellamy , per recommendation earlier:
> For step 2, wire it into https://github.com/esteblock/soroban-react. Do a PR.


I posted pr to support events in soroban-react - https://github.com/esteblock/soroban-react/pull/26, it is used in upcoming version of soroban-example-dapp, which I'm getting into shape for pr now.

**Comment by esteblock** [comment]
> 

Hello, first commit was merged. The package @soroban-react/events now is available at version 4.3.0
https://www.npmjs.com/package/@soroban-react/events/v/latest

**Comment by sreuland** [comment]
parking this ticket in 'blocked' for now as we want to wait on merging this for when the preview 9 versions of quickstart/rpc/core are avaialable.
