### ISSUE TITLE
soroban-rpc: add a flag to launch core with diagnostic events

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#474]
## What

soroban-rpc: add a flag to launch core with debug events

Add an integration test to cover launching core with new flag

## Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by 2opremio** [comment]
From https://github.com/stellar/rs-soroban-env/pull/713 I don't think Core needs to be started up in a special way to enable Diagnostic Evets.

@tsachiherman what makes you think that?

**Comment by tsachiherman** [comment]
Given that debug events are unmetered, I think that they have to be disabled by default. Otherwise, everyone would be using these instead of regular events, right ?

**Comment by 2opremio** [comment]
I am not sure, but I haven’t seen any flags in core.

@sisuresh can you confirm?

**Comment by sisuresh** [comment]
Core will have a config setting to enable debug events. The core commit linked in https://github.com/stellar/rs-soroban-env/pull/713 is just incomplete.

**Comment by 2opremio** [comment]
Ah, ok, thanks @sisuresh . Then, this ticket will entail. Either:

A:
* Adding a new flag to soroban-rpc
* Modify the captive-core backend library in the Go monorepo to translate the flag into a new Core config option

B:
* Simply add a new config parameter to the captive-core config file which enables the flag (and in turn results in the generated config flag containing the config option). This needs to be done in the Core monorepo.

**Comment by tsachiherman** [comment]
Given that the soroban-rpc needs to know this option is enabled in order to process the requests, I think that option A is the better one. It also "hides" the core implementation details, which is great.

**Comment by 2opremio** [comment]
soroban-rpc already needs to supply a core configuration file.

**Comment by paulbellamy** [comment]
Yes, I'm saying option b, for now. But nothing to do with #507.

`ENABLE_SOROBAN_DIAGNOSTIC_EVENTS=true` would be set in the file passed to: `--captive-core-config-path`

**Comment by paulbellamy** [comment]
Fixed in https://github.com/stellar/quickstart/pull/435

**Comment by orbitlens** [comment]
Got an error
```
[default FATAL] Got an exception: Failed to parse './futurenet.cfg' :Unknown configuration entry: 'ENABLE_SOROBAN_DIAGNOSTIC_EVENTS'
```
I built `stellar-core` from sources ([soroban-preview-10-July16](https://github.com/stellar/stellar-core/tree/branch-soroban-preview-10-July16) branch) and it returns me this error whenever I'm trying to launch `stellar-core` to join `futurenet`.

Is this option currently available only for the captive core? And if yes, could you please fix this?

**Comment by tsachiherman** [comment]
Did you compile soroban-core with soroban support ?
There is a configure flag that makes that happen.

**Comment by orbitlens** [comment]
> Did you compile soroban-core with soroban support ? There is a configure flag that makes that happen.

No, I didn't. Thought that the branch with the name `soroban-preview-10-July16` has Soroban support turned on by default. 

@tsachiherman Could you please point me in the right direction? How can I set this flag?
My building pipeline currently look like this:

```shell
#bash
./autogen.sh
./configure
make -j 4
```

**Comment by tsachiherman** [comment]
> > Did you compile soroban-core with soroban support ? There is a configure flag that makes that happen.
> 
> No, I didn't. Thought that the branch with the name `soroban-preview-10-July16` has Soroban support turned on by default.
> 
> @tsachiherman Could you please point me in the right direction? How can I set this flag? My compilation pipeline currently looks like this:
> 
> ```shell
> #bash
> ./autogen.sh
> ./configure
> make -j 4
> ```

I was always compiling core with the following:
```sh
make clean && ./autogen.sh && ./configure --disable-tests --enable-next-protocol-version-unsafe-for-production && make -j8
```

**Comment by orbitlens** [comment]
@tsachiherman thanks for the info. It works.
🤝
