### ISSUE TITLE
soroban-rpc: emit diagnostic events from `simulateTransaction`

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#475]
### What

soroban-rpc: emit debug events from `simulateTransaction`

### How

* Bump the env-host Rust dependency
* Modify libpreflight to also return the preflight events (both the old and the new ones)
* Modify the SimulateTransactionResponse data structure ( how ? )
* Update unit tests ( which ? )
* Implement the CLI side https://github.com/stellar/soroban-tools/issues/476

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by 2opremio** [comment]
As a result. the `simulateTransaction` JSON response (`SimulateTransactionResponse`) in soroban-rpc should include the debug events 


To do so, we should:
1. Bump the env-host Rust dependency
2. Modify `libpreflight` to also return the preflight events (both the old and the new ones)
3. Modify the `SimulateTransactionResponse` data structure
