### ISSUE TITLE
soroban-rpc: wildcard filtering, make sure equality works as expected with all the new ScVal structs in `getEvents`

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#477]
### What ? 

soroban-rpc: wildcard filtering, make sure equality works as expected with all the new ScVal structs in `getEvents`

The equality operator is actually implemented in the go monorepo so the only work required on the soroban-rpc side is updating the unit tests and making sure they still work.

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by 2opremio** [comment]
@tsachiherman Let me know if you think the work https://github.com/stellar/go/pull/4812 is enough to close this ticket

**Comment by paulbellamy** [comment]
ScVal.Equals was fixed in https://github.com/stellar/go/pull/4815, so we just need to update the tests and check it in soroban-rpc.
