### ISSUE TITLE
soroban-cli: value overhaul update - strval json/xdr parsing/serialization

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#478]
### What ? 
soroban-cli: strval json/xdr parsing/serialization

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by willemneal** [comment]
Looking into the changes made to XDR, updating will result in simpler code. However, I estimate that the refactor would take several days, since `ScVal` is used in 9 files.  The biggest change being `JSON` --> `ScVal` and `ScVal` --> `JSON`

**Comment by willemneal** [comment]
This is done.  The types are that useful for contract devs but are available now.

**Comment by tsachiherman** [comment]
> This is done. The types are that useful for contract devs but are available now.

great
