### ISSUE TITLE
soroban-cli: value overhaul update - contract deploy/install commands

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#479]
### What

soroban-cli: value overhaul update - contract deploy/install commands

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by willemneal** [comment]
If I understand this right it's that deploy/install still works with the new XDR?

**Comment by tsachiherman** [comment]
> If I understand this right it's that deploy/install still works with the new XDR?

This ticket is to ensure that when using the soroban-cli, the deployment/install would still work against the latest core release. I suspect changes to the XDR would have resulted in parameters changes that could have broken the contract deployment/install.

**Comment by willemneal** [comment]
They still pass the tests that install and deploy contracts.  However, the network tests were removed from this repo.

Is it worth adding some tests to show that the install/deploy works on a standalone network?

**Comment by willemneal** [comment]
Just manually verified it with a local standalone instance.
