### ISSUE TITLE
soroban-cli: value overhaul update - inspect ScSpecTypeDef formatting

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#481]
### What ?
soroban-cli: value overhaul update - inspect ScSpecTypeDef formatting

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by willemneal** [comment]
Does this mean it's prettier or works when inspect?

**Comment by tsachiherman** [comment]
> Does this mean it's prettier or works when inspect?

I'm going to defer this question to @paulbellamy .

**Comment by paulbellamy** [comment]
Just that it works when inspected, and formats "decently" (Or the same as it did pre value-overhaul.
