### ISSUE TITLE
soroban-cli: token wrap ScVals & footprint for the contract code

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#482]
### What ? 

soroban-cli: token wrap ScVals & footprint for the contract code

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by willemneal** [comment]
Can you provide more details?

**Comment by willemneal** [comment]
Currently we don't have any tests for `token wrap` but if it is just another contract it should be done.  I'll look into adding a test.

**Comment by paulbellamy** [comment]
if cli compiles, it should be done.
