### ISSUE TITLE
soroban-rpc: Audit and standardize logging

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#497]
### What problem does your feature solve?

Currently the logging in soroban-rpc is a bit ad-hoc. We should audit what we have, and standardize it for better ingestion by people & other tools.

### What would you like to see?

- Standardize the logging output format
- Standardize the logging severity we use for different info/warnings/errors
- Add a `--log-level` flag so operators can use what level of logging output they want.
- Add clear logging during startup so we have tools in-place to debug any potential issues there, and can understand where the service is in the startup process.
- Log all incoming jsonrpc method requests and their resolution.
  - Note, this should be two log entries, one when the request is received, and another one when it is completed, tied together with a request id. (Paul's opinion)
- Log all incoming http requests and their response with duration, etc.
- Add support for json log formatting (should this be a flag? default?)
- Audit to make sure the log outputs do not include any avoidable identifying information, or secrets.

**Comment by 2opremio** [comment]
Closing, I think I've covered everything in this ticket. @paulbellamy please reopen if you think otherwise.
