### ISSUE TITLE
soroban-rpc: Graceful shutdown for HTTP server

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#499]
### What problem does your feature solve?

When you kill soroban-rpc it may drop ongoing HTTP requests.

### What would you like to see?

We should use the HTTP server graceful shutdown mechanism to finish pending HTTP requests before shutdown.

**Comment by 2opremio** [comment]
We are already using `gopkg.in/tylerb/graceful.v1` (through `supporthttp.Run()`)

**Comment by 2opremio** [comment]
Although we should probably just be using https://pkg.go.dev/net/http#Server.Shutdown directly
