### ISSUE TITLE
soroban-rpc: Establish a benchmark baseline on (a few?) different hardware profiles

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#505]
### What problem does your feature solve?

As an operator, I'd like to be able to know what sort of hardware I need to deploy soroban-rpc, and what performance I can expect from that.
As SDF, I'd like to make sure that we don't have unexpectedly poor performance or bottlenecks in soroban-rpc before release.
As SDF, I'd like to make sure we don't introduce performance regressions going forward.

#### Ideal
Set up a weekly (monthly?) soroban-rpc performance testing job. The job should run on "reasonable" hardware, and measure CPU usage/Memory profile/Disk usage under medium and high loads.

- Optionally, it could run the job on a couple different hardware configurations and measure the difference, so we could extrapolate somewhat for recommendations.
  - Question: Is this necessary?

#### First Pass

In order to kick-off a first pass of the runbook we'd like to send to partners prior to testnet launch, we should prioritize just a single manual run that assesses performance, rather than a periodic job that consistently runs and reports results. We just want to be able to itemize in a runbook, what the hardware pre-requisites are for running an RPC (RAM, CPU, etc). This should look similar to what we have in our [docs for Horizon](https://developers.stellar.org/docs/run-api-server/prerequisites)

**Comment by stellarsaur** [comment]
A first-pass of resource consumption is covered with some [initial load testing](https://docs.google.com/document/d/1AKOTsH5XHJtOaulq1BLgTVCj4R9gkh1u0r5iDq_Gvxg/edit#heading=h.45du39dkhw62) ([self-serve load testing PR](https://github.com/stellar/soroban-tools/pull/1032/files)). This can be expanded in the future with ideas in [this design doc](https://docs.google.com/document/d/1VAJBAX7vYjI0Wbd95bqWOEcpKB01giyCSFwFzetFXlM/edit#heading=h.6tutp9nf5ktq).

Going to mark this as completed for now, but we can re-open or create another issue in the future if we want to do more involved testing.
