### ISSUE TITLE
soroban-rpc: Define and document a scaling strategy

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#506]
### What problem does your feature solve?

As an operator, I'd like to know what I should do when soroban-rpc load gets too high for my existing infrastructure.

#### Ideal

Using the results of https://github.com/stellar/soroban-tools/issues/505, we should write up a document explaining the expected scaling strategy. Isolated pods? Scale soroban-rpc with single captive-core? Do some research/thinking/modelling and decide.

#### First pass

In order to kick-off a first pass of the runbook we'd like to send to partners prior to testnet launch, we should prioritize just understanding how many requests a single instance can handle (per our the hardware profile we recommend: #505). We'd like to be able to articulate in the runbook to partners something like, "after x rps, add another RPC instance".

Scaling RPC using a single captive-core is out-of-scope for the initial first pass.

**Comment by stellarsaur** [comment]
[This doc](https://docs.google.com/document/d/1WTgjwZPp2KhatZl7y08TSSAaXW_htI8-TorwVahwyyo/edit) describes a scaling strategy with our current architecture. Closing
