### ISSUE TITLE
soroban-rpc: Runbook for infra operators

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#512]
### What problem does your feature solve?

As an infra operator I'd like to know how to deploy/run/maintain/troubleshoot soroban-rpc.

### What would you like to see?

We should write a runbook for soroban-rpc. It should include instructions how to:
- download
- build (optionally)
- deploy
- configure
  - based on https://github.com/stellar/soroban-tools/issues/507
- operate
- monitor
  - Based on https://github.com/stellar/soroban-tools/issues/496
  - and on https://github.com/stellar/soroban-tools/issues/497
- scale
  - based on https://github.com/stellar/soroban-tools/issues/506
  - and should include HW references to help provision sufficient resources based on https://github.com/stellar/soroban-tools/issues/505
- troubleshoot their instance
  - Figure out some potential common failure modes and what to do for them
  - Worst case, tell them how to gather the data we would need to help debug and how to contact us

This content should ultimately end up in [soroban-docs](https://soroban.stellar.org/docs/reference/rpc), but it's acceptable for now to have it be a google doc that we pass around to partners. This approach may also be easier to do initial review by the team. 

The docs currently have a large section describing setup using quickstart, we do *not* want that to be recommended for production instances. We should update the docs and this runbook to make that very explicit.

**Comment by sreuland** [comment]
@stellarsaur , is this intended to base or append to content from @tyvdh's  [RPC runbook](https://docs.google.com/document/d/1SIbrFWFgju5RAsi6stDyEtgTa78VEt8f3HhqCLoySx4/edit#heading=h.jtrl84su8u2c)

**Comment by stellarsaur** [comment]
This can be considered complete since we now have suitable guides for infrastructure operators in [this doc](https://docs.google.com/document/d/1SIbrFWFgju5RAsi6stDyEtgTa78VEt8f3HhqCLoySx4/edit) and [on our docs website](https://github.com/stellar/soroban-docs/pull/624)
