### ISSUE TITLE
soroban-rpc: cache the network config ledger key and provide it to the env-host during preflight

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#513]
## What

cache the network config ledger key and provide it to the env-host during preflight

Note: We already store all ledger entries, so that part should already be done.

When we run a preflight we will need to load the `NetworkConfigLedgerEntry`, and pass it's value into the `Host` object for preflight. This will let the preflight account for the configured network limits, etc.

# Epic

https://github.com/stellar/soroban-tools/issues/519

**Comment by 2opremio** [comment]
I think this is a noop (we just need to bump the `stellar/go` dependency to https://github.com/stellar/go/pull/4851 )

**Comment by 2opremio** [comment]
Closed by https://github.com/stellar/soroban-tools/pull/608
