### ISSUE TITLE
soroban-rpc: Production-ready helm-chart

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#514]
### What problem does your feature solve?

Easy way for infra providers (and ourselves) to run soroban-rpc (if they're already on k8s).

### What would you like to see?

We should take the manifests from https://github.com/stellar/kube/pull/1337, and the image from https://github.com/stellar/soroban-tools/issues/382, and combine them into a production-ready helm-chart for deploying soroban-rpc.

It should include:
- Healthchecks and automatic restarts
- Example docs for upgrading to a new version
- Persistent volumes for data, as needed
- Make sure to test upgrades when using persistent volumes

**Comment by paulbellamy** [comment]
We should probably also use a k8s ConfigMap for the config instead of having the config on a persistent volume.

**Comment by 2opremio** [comment]
For the record, there is an existing helm chart at https://github.com/stellar/helm-charts/tree/main/charts/soroban-rpc

**Comment by sreuland** [comment]
Ops is working in tandem on this aspect, and in process of refactoring the [existing helm chart](https://github.com/stellar/helm-charts/tree/main/charts/soroban-rpc) to latest rpc runtime, with review up - https://github.com/stellar/helm-charts/pull/53
