### ISSUE TITLE
soroban-cli: help output should include usage of 'source' subcommand parameter

### ISSUE THREAD

**Issue by sreuland** [stellar/soroban-tools#532]
### What version are you using?

latest build from main branch, as of 3/23, it was `a11c0371a974dc06845b1fde485ec681fe3f9e7d`

### What did you do?

`soroban contract deploy -h` or `soroban contract invoke -h`

### What did you expect to see?
the cli help console output in this context would include a section for describing how to use the `source` parameter, what values can it accept? a strkey encoded secret key, identity config name, others?

### What did you see instead?
no cli help console output on `source` parameter

**Comment by willemneal** [comment]
Hmm it seems that the alias detail isn't there but I still see `--source-account`.  Agree it could use come more examples.

**Comment by chadoh** [comment]
While adding info here, it would also be nice to fix the line breaks in the source that aren't showing up in the actual `--help` content. It might be worth looking into something like [color-print](https://crates.io/crates/color-print) as shown in [the clap 4.2 release notes](https://crates.io/crates/color-print).
