### ISSUE TITLE
soroban-rpc : add support for fee calculations

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#623]
### What ?

The rs-soroban-env now contains library functions to calculate the fees needed by a transaction, based on it's resources.
Our goal is to integrate that into simulateTransaction endpoint in soroban-rpc. This issue is about the second step in the process:
We need to use the exposed fee calculation method we previously created in https://github.com/stellar/soroban-tools/issues/622, and use it during simulateTransaction in order to calculate the suggested fees. Then, we need to modify the returned json to include the following:
( all the TransactionResources fields, that you've already used when calling compute_transaction_resource_fee )
- Number of instructions
- Number of reads
- Number of writes
- Read bytes count
- Write bytes count
- Metadata size
- Transaction size
( plus )
- Fee ( Minimal inclusion fee )
- RefundableFee

### Epic
- https://github.com/stellar/soroban-tools/issues/519

### Dependencies

- https://github.com/stellar/soroban-tools/pull/627
- https://github.com/stellar/soroban-tools/pull/628

**Comment by 2opremio** [comment]
I think this is fully addressed in https://github.com/stellar/soroban-tools/pull/636

**Comment by tsachiherman** [comment]
> I think this is fully addressed in #636

Just close both when you're done with 636, as this one was supposed to be the go side and the other on the preflightlib side.
