### ISSUE TITLE
Contract deployments should spit out the `StrKey` `Address` vs the `BytesN<32>`

### ISSUE THREAD

**Issue by tyvdh** [stellar/soroban-tools#662]
We've switched to using `StrKey` `Address` vs the `BytesN<32>` so we should stop spitting out less usable `BytesN<32>` hashes.

The two places I'm aware of would be `contract deploy` and `lab token wrap`. There may be others?

Dependent on:
https://github.com/stellar/soroban-tools/issues/660

Related to:
https://github.com/stellar/soroban-tools/issues/661

**Comment by paulbellamy** [comment]
Part of https://github.com/stellar/soroban-tools/issues/403
