### ISSUE TITLE
soroban-rpc: implement state-compaction support

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#664]
### What ?
The goal of this task is to implement a state compaction support in the soroban-rpc so that it would behave equal to the core.

### Entry Creation

- [x] Soroban-RPC should store the `expirationLedgerSeq` field for ContractDataEntry and ContractCodeEntry type LedgerEntries.
- [x] Nice-to-have: The `getLedgerEntries` should include the entry's expirationLedgerSeq value if set. This might already happen automatically, but double-check it.

Normal ledger entry creation, as before, except ContractDataEntry and ContractCodeEntry have a new xdr field, `expirationLedgerSeq`.

### Entry Extension

- [x] When Soroban-RPC sees an EXPIRATION_EXTENSION, it should update the stored entry with the new expirationLedgerSeq.

Users can extend the expirationLedgerSeq via several ways (manual/automatic/host-fn). But whichever way they do, a LedgerEntry will be emitted.

The ContractDataEntry and ContractCodeEntry have a new subtype called: [EXPIRATION_EXTENSION](https://github.com/stellar/stellar-xdr/blob/956da0a0d6020efd539f3adbc6f7a0d4876478e4/Stellar-ledger-entries.x#L522-L523). That just includes the ledger entry key, and the new expirationLedgerSeq, but doesn’t re-emit the full entry value.

### Entry Expiration

- [x] v1: Deny access to ledger entries where `expirationLedgerSeq` is in the past.
- [ ] v2: Allow access to expired entries in `simulateTransaction`, but record them and return that to the client.

Entries at this stage should *not* be deleted from Soroban-RPC. Users can still extend the entry’s expiration to make it accessible again.

Nothing is emitted by Core at this stage. It is up to downstream systems to track the `expirationLedgerSeq`, and make sure that entries where the expiration is in the past are not made available to contracts.

### Entry Deletion

- [ ] Soroban-RPC does not do long-term storage, so all entries which the new LedgerCloseMetaV2 lists as “evicted” should be deleted.

The new xdr type [LedgerCloseMetaV2](https://github.com/stellar/stellar-xdr/blob/956da0a0d6020efd539f3adbc6f7a0d4876478e4/Stellar-ledger.x#L493-L524) now includes 3 new fields to support state expiration:
```
    // Size in bytes of BucketList, to support downstream
    // systems calculating storage fees correctly.
    uint64 totalByteSizeOfBucketList;

    // Expired temp keys that are being evicted at this ledger.
    LedgerKey evictedTemporaryLedgerKeys<>;

    // Expired restorable ledger entries that are being
    // evicted at this ledger.
    LedgerEntry evictedRestorableLedgerEntries<>;
```

Specifically, when an entry is deleted from the core bucketlist it will be included in either the `evictedTemporaryLedgerKeys`, or the `evictedRestorableLedgerEntries`.

The temporary keys are simply dropped.

The Restorable entries should be picked up by the EvictedStateArchiveNodes for long-term storage.

### Horizon

Update Horizon's ContractData ingest processor to make sure that balances are maintained correctly when they are expired/evicted/restored.

I expect this is a no-op, (aside from the xdr updates), because when it is restored the full balance is emitted as the new ledger-entry. But confirm with @SirTyson when he is back.

**Comment by SirTyson** [comment]
I know this is closed but wanted to comment for completeness sake. 

> Update Horizon's ContractData ingest processor to make sure that balances are maintained correctly when they are expired/evicted/restored. I expect this is a no-op, (aside from the xdr updates), because when it is restored the full balance is emitted as the new ledger-entry. But confirm with @SirTyson when he is back.

This is correct, restored entries follow the same path as newly created entries and emit the same meta as if the entry was created for the first time. Depending on the DB you use, this may not necessarily be a no-op. If you distinguish between modification and creation paths, you may need to make a modification, otherwise you should be fine.
