### ISSUE TITLE
soroban-rpc: update to support newly formed Auth + single invoked host function

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#682]
## What ?

soroban-rpc: update to support newly formed Auth + single invoked host function

## Epic

https://github.com/stellar/soroban-tools/issues/657

**Comment by sreuland** [comment]
on scope of expected changes, is this specific to api endpoints and/or ingestion functionality, will it require any preflight changes?

**Comment by tsachiherman** [comment]
When writing up this issue I wasn't fully aware of the vast range of changes introduced in the recent xdr, so to answer your question - it could either be "all of the above", or that we can update the scope of this one and create additional issues.

**Comment by tomerweller** [comment]
Is this complete by #703?

**Comment by tsachiherman** [comment]
It also requires the pr that add the two operations + unit tests.

**Comment by tsachiherman** [comment]
The merge of the PR is done, and I've broken the unit tests onto a separate ticket.
