### ISSUE TITLE
soroban-cli install instructions are incomplete on Ubuntu 22.04

### ISSUE THREAD

**Issue by jacekn** [stellar/soroban-tools#729]
### What version are you using?

I tried to use 0.8.0

### What did you do?

I tried to install soroban cli using [docs](https://soroban.stellar.org/docs/getting-started/setup) on Ubuntu 22.04 on amd64 platform.

Exact steps I followed:
1. I run `cargo install --locked --version 0.8.0 soroban-cli`. This failed with the following:
```
   Compiling proc-macro2 v1.0.56
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)
```
2. To work around the problem I install gcc using `sudo apt-get install gcc`
3. I retried `cargo install --locked --version 0.8.0 soroban-cli`. This time if failed with:
```
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/tmp/cargo-install6vzfsz/release/build/link-cplusplus-cb722335163fd5c9/out/ffae553e737ce720-dummy.o" "-c" "/tmp/cargo-install6vzfsz/release/build/link-cplusplus-cb722335163fd5c9/out/dummy.cc"

  --- stderr

  error occurred: Failed to find tool. Is `c++` installed?
```
4. To work around this I installed c++ using `sudo apt install g++`

### What did you expect to see?

I expected install instructions to work on a vanilla Ubuntu 22.04 system.

### What did you see instead?

I had to install two Ubuntu packages in order to install the CLI: `gcc` and `g++`

**Comment by willemneal** [comment]
You should be able to use `cargo-binstall`, which would download a built binary.

First need to install cargo-binstall:
```
cargo install cargo-binstall
```

[Or install `cargo-binstall` as they recommend](https://github.com/cargo-bins/cargo-binstall#installation):
```
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
```

Then can install soroban-cli:
```
cargo binstall soroban-cli
```

**Comment by jacekn** [comment]
@willemneal thank you for extra info. I have not tested this but if those commands work and avoids pulling build dependencies then I'd fully support switching official docs to them.

**Comment by stellarsaur** [comment]
`cargo bininstall soroban-cli` will be added to the docs (as well as updating `cargo install` instructions to include `gcc` and `g++`) as part of [this issue](https://github.com/stellar/soroban-tools/issues/1083)
