### ISSUE TITLE
no such command: `contract`

### ISSUE THREAD

**Issue by tyvdh** [stellar/soroban-tools#738]
When a child command is incorrect the CLI is saying the the wrong command is missing.

e.g. `soroban contract binings typescript --wasm` (notice "bindings" is misspelled)

```bash
% soroban contract binings typescript --wasm target/wasm32-unknown-unknown/release/colorglyph.wasm -h
error: no such command: `contract`
        
        View all installed plugins with `soroban --list`
```

Contract obviously _does_ exist, it's "binings" that's incorrect.

**Comment by chadoh** [comment]
I believe this is an error in `clap`, but I haven't been able to find a related bug report in their repo. I'll see if I can reproduce it in a new test case for them.

**Comment by chadoh** [comment]
Ok, I've confirmed that this is not a bug in clap: https://github.com/AhaLabs/clap/pull/1
