### ISSUE TITLE
Improve generated TypeScript bindings

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-tools#780]
TBD: Needs clarity.

Related:
 - [x] https://github.com/stellar/soroban-tools/pull/770
 - [x] https://github.com/stellar/soroban-tools/pull/753

Is there more we can define here that can be better?

**Comment by willemneal** [comment]
I was about to make an issue for it, but we need to add proper tests.

**Comment by Shaptic** [comment]
Yeah tests are a big one, and I think there's been enough feedback on the bindings to flesh this issue out beyond the two I linked? Feel free to edit the issue text.
