### ISSUE TITLE
soroban-cli: fix the contract restore operation following core update

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#793]
### What ?

Following core's update, core is going to emit <previous state> + <update> for a restore operation rather then just a <create>.
That means that the code in https://github.com/stellar/soroban-tools/blob/99ac6974cf8327a361cef19e48e92947f4a96d2d/cmd/soroban-cli/src/commands/contract/restore.rs#L186-L188
is no longer valid, and would break.

**Comment by willemneal** [comment]
I don't understand:

> core is going to emit + for a restore operation rather then just a .

**Comment by tsachiherman** [comment]
Futurenet was just redeployed. Mind attempting to create an entry that you'll try to restore tomorrow ?

**Comment by willemneal** [comment]
Sure

**Comment by willemneal** [comment]
It seems the default for entries to expire is near 86,398 ledger entries. Which is about 5 days. So I just installed some other contracts so I guess we'll have to wait 5 more days. (unless there is a way to prevent the default? or set it to lower)?

**Comment by tsachiherman** [comment]
@sisuresh would it be any lower if this would be a standalone network ? how can we test this ?

**Comment by willemneal** [comment]
@2opremio 

Just tried
Using the latest release:
```zsh
soroban --vv contract bump --ledgers-to-expire 0 --durability persistent \
    --wasm increment/target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm \
    --rpc-url https://rpc-futurenet.stellar.org:443 \
    --network-passphrase 'Test SDF Future Network ; October 2022'
```

Tells me that `latest_ledger: 96508` and that the expriation is `98046`.  So  still have a couple more hours to go!

**Comment by 2opremio** [comment]
🤞

**Comment by willemneal** [comment]
I'm regretting now installing more.  Not being able to set the minimum makes this very hard to test.

**Comment by sisuresh** [comment]
> @sisuresh would it be any lower if this would be a standalone network ? how can we test this ?

Sorry I missed the notification for this. On a standalone network, we'd use the default, which would be 4096. If you're using standalone though, is it easy to update the core config? If so, you could  set `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` in the core config file to something lower.

**Comment by 2opremio** [comment]
Note that `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` was just incorporated

**Comment by 2opremio** [comment]
> I'm regretting now installing more. Not being able to set the minimum makes this very hard to test.

Does this mean you run out of contracts to restore?

**Comment by 2opremio** [comment]
> Note that `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` was just incorporated

The debian package version on top of preview 10 supporting  `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` is `19.12.1-1409.b8cf8bfcc.focal~soroban`

There is a matching docker image `2opremio/stellar-core:19.12.1-1409.b8cf8bfcc.focal-soroban`

Also note that `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` still isn't supported in the captive core config file until https://github.com/stellar/go/pull/4983 lands (although it probably doesn't matter for captive core, @sisuresh ? )

**Comment by 2opremio** [comment]
I think I will be able to address this once https://github.com/stellar/soroban-tools/pull/821 works (it's currently blocked)

It will allow me to expire persistent entries after 30 ledgers.

**Comment by 2opremio** [comment]
Fixed by https://github.com/stellar/soroban-tools/pull/824
