### ISSUE TITLE
RPC Docker not working

### ISSUE THREAD

**Issue by jcx120** [stellar/soroban-tools#841]
### What version are you using?
Preview 10 
https://hub.docker.com/r/stellar/soroban-rpc

### What did you do?
Download and try to run the RPC

### What did you expect to see?
It working, not failing

### What did you see instead?

When trying to run the RPC from the docker, which is supposed to be isolated from other stuff from the Quickstart (eg Horizon), you get this error:

```
$ sudo docker run   --name soroban-rpc   --rm       -p 8002:8000   -v ${PWD}/templates/captive-core-config.toml.j
2:/etc/default/stellar-captive-core.toml   --mount source=soroban-rpc,target=/var/lib/stellar/   -e CAPTIVE_CORE_CONF
IG_PATH=/etc/default/stellar-captive-core.toml   stellar/soroban-rpc:0.9.2   --captive-core-use-db
Unable to find image 'stellar/soroban-rpc:0.9.2' locally
0.9.2: Pulling from stellar/soroban-rpc
01085d60b3a6: Pull complete
e8eb1cbb0a84: Pull complete
Digest: sha256:69c8094b0581a4d60669efa42120e8186d7db6bed0a7177429984bcbc2b0cf30
Status: Downloaded newer image for stellar/soroban-rpc:0.9.2
time="2023-08-03T20:16:44.215Z" level=fatal msg="could not create captive core" error="Error connecting to ALL histor
y archives.: No history archives provided" pid=1
```
Also noticed a reference to Horizon URL:

```
# for now rpc requires access to horizon, this will change.
HORIZON_URL=http://localhost:8000/
```
Other errors also observed:

`time="2023-08-03T15:57:25.220Z" level=fatal msg="Invalid captive core toml" error="invalid captive core toml: BucketListDB enabled in captive core config file, requires Horizon flag --captive-core-use-db" pid=1
`
`level=fatal msg="could not create captive core" error="Error connecting to ALL history archives.: No history archives provided" pid=1`

Not sure if this is related to this bug:
https://github.com/stellar/quickstart/issues/456

**Comment by sreuland** [comment]
the published `stellar/soroban-rpc` image comes from the newly introduced `Dockerfile.release` added to repo from this recent PR - https://github.com/stellar/soroban-tools/pull/710/files. 

How did you come up with that docker run statement, was it doc'd somewhere, I think the [stellar/helm-charts/soroban-rpc](https://github.com/stellar/helm-charts/blob/main/charts/soroban-rpc/templates/soroban-rpc-sts.yaml), have an example of generating the configurations for the image, which was used in other deployment and seemed to work. you would need to checkout stellar/helm-charts, install the `helm` cli tool locally, and then run `helm template -f charts/soroban-rpc/values.yaml charts/soroban-rpc/` and it will generate a screen output of the real config, which may provide a good example of the current config that the `stellar/soroban-rpc` image expects, the setup aggregates settings into a config map which is then provided as as a single file to the soroban-rpc `--config-file` option. 

cc'ing @jacekn

**Comment by jcx120** [comment]
@sreuland Do we have it documented on the proper way to run the service from Docker? Is it the similar to Quickstart?

```
docker run --rm -it \
    -p "8000:8000" \
    --name stellar \
    stellar/<...>:soroban-dev \
    --standalone \
    --enable-soroban-rpc
```

**Comment by sreuland** [comment]
This newer`stellar/soroban-rpc` image is different than `stellar/quickstart:soroban-dev` and does not have any common runtime parameters and can't be invoked in the same way. The new [Dockerfile.release](https://github.com/stellar/soroban-tools/blob/main/cmd/soroban-rpc/docker/Dockerfile.release) was added just recently to support k8s deployments, docs for running it in non-k8s as a `docker run` have not been created, but checking out locally [soroban rpc helm chart](https://github.com/stellar/helm-charts/blob/main/charts/soroban-rpc/templates/soroban-rpc-sts.yaml) can provide a good reference of how to run the image, it aggregates all the rpc and captive core runtime params into k8s config maps `soroban-rpc.cfg`  and `stellar-captive-core.cfg`.  running `helm template -f charts/soroban-rpc/values.yaml charts/soroban-rpc/` will print that to screen:

```
helm-charts$ helm template -f charts/soroban-rpc/values.yaml charts/soroban-rpc/
---
# Source: soroban-rpc/templates/soroban-rpc-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-soroban-rpc
  namespace: default
  labels:
    app: release-name-soroban-rpc
    chart: soroban-rpc-0.1.0-beta.1
    release: release-name
    heritage: Helm
data:
  soroban-rpc.cfg: |
    CAPTIVE_CORE_CONFIG_PATH="/config/stellar-captive-core.cfg"
    CAPTIVE_CORE_STORAGE_PATH="/var/lib/stellar/captive-core"
    CAPTIVE_CORE_USE_DB=true
    STELLAR_CORE_BINARY_PATH="/usr/bin/stellar-core"
    ENDPOINT="0.0.0.0:8000"
    ADMIN_ENDPOINT="0.0.0.0:6061"
    DB_PATH="/var/lib/stellar/soroban-rpc-db.sqlite"
    STELLAR_CAPTIVE_CORE_HTTP_PORT=11626
    FRIENDBOT_URL="https://friendbot-futurenet.stellar.org/"
    NETWORK_PASSPHRASE="Test SDF Future Network ; October 2022"
    HISTORY_ARCHIVE_URLS="http://history-futurenet.stellar.org"
    CHECKPOINT_FREQUENCY=64
    
  stellar-captive-core.cfg: |
    DATABASE="sqlite3:///var/lib/stellar/stellar-captive-core.db"
    HTTP_PORT=11626
    PUBLIC_HTTP_PORT=true
    PEER_PORT=11625
    EXPERIMENTAL_BUCKETLIST_DB=true
    EXPERIMENTAL_BUCKETLIST_DB_INDEX_PAGE_SIZE_EXPONENT=12
    NETWORK_PASSPHRASE="Test SDF Future Network ; October 2022"
    UNSAFE_QUORUM=true
    
    [[HOME_DOMAINS]]
    HOME_DOMAIN="futurenet.stellar.org"
    QUALITY="MEDIUM"
    [[VALIDATORS]]
    NAME="sdf_futurenet_1"
    HOME_DOMAIN="futurenet.stellar.org"
    PUBLIC_KEY="..."
    ADDRESS="..."
    HISTORY="curl -sf http://.../{0} -o {1}"
    [[VALIDATORS]]
    NAME="sdf_futurenet_2"
     HOME_DOMAIN="futurenet.stellar.org"
    PUBLIC_KEY="..."
    ADDRESS="..."
    HISTORY="curl -sf http://.../{0} -o {1}"
    [[VALIDATORS]]
    NAME="sdf_futurenet_3"
     HOME_DOMAIN="futurenet.stellar.org"
    PUBLIC_KEY="..."
    ADDRESS="..."
    HISTORY="curl -sf http://.../{0} -o {1}"
---


```

The two config map entries are just key-values each on separate lines, they can be copied to plain text files `soroban-rpc.cfg` and `stellar-captive-core.cfg` and used in `docker run` locally, passing the `soroban-rpc.cfg` file to `stellar/soroban-rpc`:


`docker run stellar/soroban-rpc --config-file <path/to/your/soroban-rpc.cfg>`.
