### ISSUE TITLE
soroban-rpc: Grafana dashboard improvement

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#850]
Following on from https://github.com/stellar/soroban-tools/issues/669

We should have a soroban-rpc specific dashboard on grafana. We can base it on the horizon dashboard, which has proven useful. It should have easy top-line metrics to tell "if it is working", then sections to help you drill down and investigate issues.

This should specifically work for rpc-futurenet.stellar.org.

**Comment by paulbellamy** [comment]
It would be nice if (when developing this) we set up grafana locally, and tested a few different failure modes to see how useful it is.

**Comment by sreuland** [comment]
a starting template of dashboard - https://grafana.stellar-ops.com/d/ut9rEquVz/soroban-rpc?orgId=1&var-Datasource=Prometheus-kube001-dev&from=now-1h&to=now
