### ISSUE TITLE
soroban-rpc: duplicate the futurenet deployment of soroban-rpc onto testnet

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#908]
### What ?

The goal of this issue is to complete the deployment of a soroban-rpc testnet, prior to the testnet release.
In order to do so, we will be using the existing preview 10 binaries, and deploy these to testnet.

The *expected* outcome is that the deployment would not be usable in any meaningful way, other then to test our ability to deploy a testnet soroban-rpc instance.

### child issue

https://github.com/stellar/kube/pull/1628

**Comment by sreuland** [comment]
ok, I think to enable this test deployment, I will update https://github.com/stellar/kube/pull/1628, and add manifests for deploying rpc/testnet to a new namespace `soroban-rpc-testnet-dev`

**Comment by sreuland** [comment]
closing, https://github.com/stellar/kube/pull/1628 merged, and after some de-bugging related to incorrect manifest was fixed also - https://github.com/stellar/kube/pull/1651, the new namespaces for testnet have been created with correct resources defined(statefulset, configmaps, ingress), and scaled to replicas=0 for now, so, no pods running, will need to do a follow-on pr to change that to replicas=1 and the correct image ref for docker rpc release image once testnet is upgraded.
