### ISSUE TITLE
Soroban CLI Error: Missing Result in Successful Response

### ISSUE THREAD

**Issue by upendra-eth** [stellar/soroban-tools#970]
I'm encountering an error while deploying a Soroban contract using the Soroban CLI. Here's the command I'm using:

soroban contract deploy
--wasm target/wasm32-unknown-unknown/release/hello_soroban.wasm
--source alice
--network futurenet

error: Missing result in successful response

**Comment by willemneal** [comment]
What version?

**Comment by upendra-eth** [comment]
soroban --version
soroban 0.9.1 (b5e8586344ab52c0a1b8988b44b0c4e516a473ce)
soroban-env 0.0.17 (400d806387140553e4e685d232deb3a807ec0e36)
soroban-env interface version 85899345971
stellar-xdr 0.0.17 (0f16673441898162c9996da6117be2280ef8fd84)
xdr next (e372df9f677961aac04c5a4cc80a3667f310b29f)

**Comment by upendra-eth** [comment]
even in latest one

**Comment by willemneal** [comment]
Latest being 20.0.0-rc1?

Also is the account funded?

The newest cli has 'config identity fund' command

**Comment by upendra-eth** [comment]
i have used 20.0.0-rc1 , 20.0.0-rc2  and yes account is funded

**Comment by upendra-eth** [comment]
and now i updated the cli to new version - 20.0.0-rc4 so i am not gitting this error

**Comment by upendra-eth** [comment]
But now i am getting new error - [error, Error(WasmVm, InvalidInput)], data:["contract pre-release number for current protocol does not match host", 51, 57]

Caused by:
    HostError: Error(WasmVm, InvalidInput)
    
    Event log (newest first):
       0: [Diagnostic Event] topics:[error, Error(WasmVm, InvalidInput)], data:["contract pre-release number for current protocol does not match host", 51, 57]

**Comment by willemneal** [comment]
Need to recompile your contract. 

Also for future reference you can add --vv after soroban, e.g. `soroban --vv`, to get very verbose logging.

**Comment by stellarsaur** [comment]
Closing this since there has been no further discussion in awhile. Please recompile your contract and reopen if you're still experiencing this issue.
