### ISSUE TITLE
CLI: Remove sandbox mode

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#983]
### What

Remove sandbox mode and all functionality supporting it.

### Why

Most folks are using the stellar/quickstart docker image or a deployed soroban-rpc on futurenet/testnet instead of sandbox.

Over time we have not maintained the sandbox functionality consistently with the soroban-rpc and network.

A discussion was started on Discord to field feedback from the ecosystem:
https://discord.com/channels/897514728459468821/1150948802107277392

@namankumar also did user research and discovered that very few folks are using sandbox mode.

We've got limited resources and can reduce the cost of maintaining the CLI by removing this functionality. It should also make some areas of the CLI easier to evolve since there won't be two different code paths for each operation.

cc @namankumar @tomerweller 
```[tasklist]
### Tasks
- [ ] Update docs to use docker image (not testnet) instead of sandbox
- [ ] Remove code from soroban-cli
```

**Comment by leighmcculloch** [comment]
The soroban-docs rely on the use of sandbox mode in most tutorials and guides. Part of this work needs to be the updating of the guides to instead include instructions for running the docker container, configuring it as a local network for the soroban-cli to communicate with and then using it.

**Comment by Shaptic** [comment]
Disagreed with `[P2 Deferrable]`: I think updating the docs is a P0 must as it's just creating excessive confusion in the community.
