### ISSUE TITLE
Contract deployment error -  [error, Error(WasmVm, InvalidInput)], data:["contract pre-release number for current protocol does not match host", 51, 57]

### ISSUE THREAD

**Issue by upendra-eth** [stellar/soroban-tools#993]
### What version are you using?
soroban-cli v20.0.0-rc4

### What did you do?
[https://stellar.stackexchange.com/questions/6239/unable-to-deploy-hello-world-contract-using-soroban-cli-tool](url)

### What did you expect to see?
Contract addres 

### What did you see instead?
error massage 

i tried using command - soroban contract deploy --wasm target/wasm32-unknown-unknown/release/hello_soroban.wasm --source alice --network futurenet

I tried on futurenet and test net both

used soroban --version -- soroban 20.0.0-rc4

i have attached screenshot in stack exchange link

**Comment by willemneal** [comment]
The error means the contract needs to be recompiled. 

I do think this error should be clearer. Perhaps it could check before deploying.

**Comment by upendra-eth** [comment]
ok thanks ... but i have tried after cargo clean and then compiling again and also i am using a very simple smart contract of hallo world from documents . so what can be reaseon

**Comment by willemneal** [comment]
What is the version of the sdk? I should have been clearer. It means that it needs to be recompiled with an sdk that is compatible with futurenet.

**Comment by stellarsaur** [comment]
Going to close this since it's been almost 2 months with no further discussion. Please try to recompile with an SDK that is compatible with futurenet and re-open if you're still experiencing an issue.
