### ISSUE TITLE
RPC: getNetwork on testnet returns incorrect friendbot address

### ISSUE THREAD

**Issue by willemneal** [stellar/soroban-tools#994]
### What version are you using?

20.0.0-rc4

### What did you do?

Tried to fund an account on testnet.

### What did you expect to see?

The docs provide the following address:
```
 curl "https://friendbot.stellar.org/?addr=$(soroban config identity address alice)"
```

### What did you see instead?

Adding some logging it returns:
```
https://friendbot-testnet.stellar.org/?addr=GABPJHI336IYGCFXFYNZVMS3FZIZ46BC57NMKB47FXY675ZPIDREAG7D
```

**Comment by tsachiherman** [comment]
fixing approach:
1. First, fix all the existing locations that refers to friendbot-testnet.stellar.org and change these to friendbot.stellar.org
2. Then, redirect all traffic from friendbot-testnet.stellar.org to friendbot.stellar.org

These changes should ensure that all the existing clients would be fully functional while future clients would use the correct url. In the future, we should be able to drop  friendbot-testnet.stellar.org completely.

**Comment by tsachiherman** [comment]
closing as both the above steps were completed. The fact that the rpc is still returning the wrong url would not have any downside, and it would "magically" get fixed on the next update.
