### ISSUE TITLE
CLI: integration test, verify token contract xfer/burn methods

### ISSUE THREAD

**Issue by sreuland** [stellar/soroban-tools#995]
### What problem does your feature solve?
no test coverage on token contract xfer/burn methods

### What would you like to see?
two tests that create a token contract from classic asset, then. execute token contract xfer and burn methods from the two test infrastructures in the soroban-tools repo:

* the cli tested from a go test  - https://github.com/stellar/soroban-tools/blob/main/cmd/soroban-rpc/internal/test/cli_test.go

* the cli tested from a rust test

**Comment by willemneal** [comment]
@sreuland what is the benefit of both places? Both would invoke the CLI and make requests to the go server.

**Comment by sreuland** [comment]
if the cli_test.go ultimately executes the same internal rust code path, then can adjust that requirement and remove the rust integration test and just focus on cli_test.go for coverage.
