### ISSUE TITLE
CLI: invoke panicks when no `--` included

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#999]
### What version are you using?

```console
❯ soroban version
soroban 20.0.0-rc3 (7cc2f46b4b83a94375e33f738d30f0bb824ea9a5)
soroban-env 20.0.0-rc2 (8c63bff68a15d79aca3a705ee6916a68db57b7e6)
soroban-env interface version 85899345977
stellar-xdr 20.0.0-rc1 (d5ce0c9e7aa83461773a6e81662067f35d39e4c1)
xdr curr (9ac02641139e6717924fdad716f6e958d0168491)

```

### What did you do?

Ran the `contract invoke` sub command without any parameters other than the contract ID:

```console
❯ SOROBAN_RPC_URL=... SOROBAN_NETWORK_PASSPHRASE=... soroban contract invoke --id C...
```

### What did you expect to see?

I expected to see some default help output, as if I had run the command with `-- --help`:

```console
❯ SOROBAN_RPC_URL=... SOROBAN_NETWORK_PASSPHRASE=... soroban contract invoke --id C... -- --help
Usage: C... [COMMAND]

Commands:
  counter  
  count    
  help     Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

### What did you see instead?

A panick.

```console
❯ SOROBAN_RPC_URL=... SOROBAN_NETWORK_PASSPHRASE=... soroban contract invoke --id C...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/leighmcculloch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/soroban-cli-20.0.0-rc3/src/commands/contract/invoke.rs:188:66
```

**Comment by willemneal** [comment]
I've also been considering making the generated cli interactive.

**Comment by leighmcculloch** [comment]
That would be very cool, although that wouldn't need to be mutually exclusive with the existing UI. The existing UI is advantageous as it's usable in scripts, so I think there's strong value in retaining it and adding an interactive API in addition? I imagine both can be powered by much of the same logic.

**Comment by willemneal** [comment]
Yeah I've also had some issues in some shells, when using the clap interactive crate. Still seems like an easy addition that would be none breaking since the normal CLI is still available.

**Comment by willemneal** [comment]
I looked more into this and the tools that I found for generating an interactive prompt all use `derive` and not a builder. So while I would still like to find a way to do it interactively it's not as easy as I had hoped.
